# Generated by Django 3.2.4 on 2026-06-02 20:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acordo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('vl_emprestimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vl_juros_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dt_acordo', models.DateField(blank=True, null=True)),
                ('vl_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('qt_parcela', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emprestimo_referencia', models.IntegerField(blank=True, null=True)),
                ('dt_cobranca', models.DateField(blank=True, null=True)),
                ('vl_capital_giro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'emp_acordos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcordoParcela',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nr_parcela', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('dt_vencimento', models.DateField(blank=True, null=True)),
                ('dt_pagamento', models.DateField(blank=True, null=True)),
                ('tp_pagamento', models.CharField(blank=True, max_length=40, null=True)),
                ('status_pagamento', models.CharField(blank=True, max_length=40, null=True)),
                ('vl_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vl_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qtd_tt_parcelas', models.IntegerField(blank=True, null=True)),
                ('dt_prev_pag_parcial_restante', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emp_acordo_parcelas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=120, null=True)),
                ('complemento', models.CharField(blank=True, max_length=120, null=True)),
                ('bairro', models.CharField(blank=True, max_length=60, null=True)),
                ('cidade', models.CharField(blank=True, max_length=60, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('is_blacklisted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emp_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('vl_emprestimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vl_capital_giro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('perc_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vl_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qt_parcela', models.IntegerField(blank=True, null=True)),
                ('vl_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('dt_emprestimo', models.DateField(blank=True, null=True)),
                ('dt_cobranca', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emp_emprestimos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmprestimoParcela',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nr_parcela', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('dt_vencimento', models.DateField(blank=True, null=True)),
                ('dt_pagamento', models.DateField(blank=True, null=True)),
                ('tp_pagamento', models.CharField(blank=True, max_length=40, null=True)),
                ('status_pagamento', models.CharField(blank=True, max_length=40, null=True)),
                ('vl_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vl_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qtd_tt_parcelas', models.IntegerField(blank=True, null=True)),
                ('dt_prev_pag_parcial_restante', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emp_emprestimo_parcelas',
                'managed': False,
            },
        ),
    ]
