# Generated by Django 3.2.4 on 2023-07-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numLogr', models.CharField(blank=True, max_length=255, null=True)),
                ('complLogr', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
