# Generated by Django 3.2.4 on 2026-06-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230724_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'bancos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CanalAquisicaoCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'canal_aquisicao_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'convenios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'corretores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuturoContrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_rep_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_rep_legal', models.CharField(blank=True, max_length=20, null=True)),
                ('convenio', models.CharField(blank=True, max_length=100, null=True)),
                ('operacao', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('vl_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('dt_concessao_beneficio', models.DateField(blank=True, null=True)),
                ('dt_efetivacao_emprestimo', models.DateField(blank=True, null=True)),
                ('representante_legal', models.BooleanField(blank=True, null=True)),
                ('iletrado', models.BooleanField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'futuros_contratos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NaturezaDespesa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'natureza_despesas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'operacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreContrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('promotora', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_digitacao', models.DateField(blank=True, null=True)),
                ('nr_contrato', models.CharField(blank=True, max_length=60, null=True)),
                ('no_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('convenio', models.CharField(blank=True, max_length=100, null=True)),
                ('operacao', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('vl_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qt_parcelas', models.IntegerField(blank=True, null=True)),
                ('vl_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dt_pag_cliente', models.DateField(blank=True, null=True)),
                ('porcentagem', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('corretor', models.CharField(blank=True, max_length=100, null=True)),
                ('tabela', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=20, null=True)),
                ('status_comissao', models.CharField(blank=True, max_length=30, null=True)),
                ('iletrado', models.BooleanField(blank=True, null=True)),
                ('documento_salvo', models.BooleanField(blank=True, null=True)),
                ('user_id_created', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato_criado', models.BooleanField(blank=True, default=False, null=True)),
                ('dt_pag_comissao', models.CharField(blank=True, max_length=255, null=True)),
                ('vl_comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('representante_legal', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pre_contratos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'promotoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lojas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('sg_loja', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'core_lojas',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'managed': False},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE core_despesa ADD COLUMN IF NOT EXISTS id_loja integer NULL;",
                    reverse_sql=None,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='despesa',
                    name='id_loja',
                    field=models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
    ]
