# Generated by Django 3.2.4 on 2026-06-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE users_module_user "
                        "ADD COLUMN IF NOT EXISTS sistema_origem varchar(50) NULL;"
                    ),
                    reverse_sql=None,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='sistema_origem',
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
